#!/bin/bash

# save original working dir
OLD_PWD=`pwd`

# create tmp directory
TMP_DIR="/home/${USER}/.tmp/"
TMP_FILE="git-unmerged.output"
mkdir -p $TMP_DIR

# determine current branch
if [ $1 ]
then
	CURRENT_BRANCH=$1
fi
if [ ! $1 ]
then
	CURRENT_BRANCH=`git branch | grep '*' | cut --delimiter=* -f 2 | cut -c 2-`
fi

# determine tracking branch
until [ -d .git/ ]; do
	cd ..
done
GIT_CONFIG=`pwd`"/.git/config"
REMOTE_BRANCH=`cat $GIT_CONFIG | grep --after-context=2 'branch "'$CURRENT_BRANCH | tail -1 | cut --delimiter=/ -f 3`
REMOTE_NAME=`cat $GIT_CONFIG | grep --after-context=2 'branch "'$CURRENT_BRANCH | tail -2 | head -1 | cut --delimiter== -f 2 | cut -c 2-`
TRACK=$REMOTE_NAME/$REMOTE_BRANCH

# generate the output
echo "Commits not merged to ${TRACK}:" > $TMP_DIR$TMP_FILE
git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset %an' --abbrev-commit --date=relative $TRACK..$CURRENT_BRANCH >> $TMP_DIR$TMP_FILE

# render the output in less
cat $TMP_DIR$TMP_FILE | less -RcifqMSj5

# clean up
rm -rf $TMP_DIR
cd $OLD_PWD
